-- Hand-written (not generated by `prisma migrate diff`) — CHECK
-- constraints, partial unique indexes, and triggers aren't expressible in
-- schema.prisma for this Prisma version, same reasoning as the
-- 20260904185506_harden_inventory_movement migration. PL-P2-05, first
-- production-lifecycle review: none of the trip/ticket/return/memo
-- invariants the application layer already enforces had any database-
-- level backstop. Preflighted against the real database before writing
-- this file — every one of the checks below currently matches zero
-- existing rows (confirmed with an explicit COUNT/GROUP BY query per
-- constraint), so nothing here can conflict with production data.

-- ---------------------------------------------------------------------
-- BatchTicket
-- ---------------------------------------------------------------------
ALTER TABLE "BatchTicket" ADD CONSTRAINT "BatchTicket_status_check"
  CHECK (status IN ('RELEASED', 'BATCHING', 'COMPLETE', 'CANCELLED'));

ALTER TABLE "BatchTicket" ADD CONSTRAINT "BatchTicket_volumeM3_positive_finite"
  CHECK ("volumeM3" > 0 AND "volumeM3" < 'Infinity'::float8);

-- ---------------------------------------------------------------------
-- BatchComponentActual
-- ---------------------------------------------------------------------
ALTER TABLE "BatchComponentActual" ADD CONSTRAINT "BatchComponentActual_targetMassKg_positive_finite"
  CHECK ("targetMassKg" > 0 AND "targetMassKg" < 'Infinity'::float8);

ALTER TABLE "BatchComponentActual" ADD CONSTRAINT "BatchComponentActual_actualMassKg_nonneg_finite"
  CHECK ("actualMassKg" IS NULL OR ("actualMassKg" >= 0 AND "actualMassKg" < 'Infinity'::float8));

ALTER TABLE "BatchComponentActual" ADD CONSTRAINT "BatchComponentActual_reclaimCreditMassKg_nonneg_finite"
  CHECK ("reclaimCreditMassKg" >= 0 AND "reclaimCreditMassKg" < 'Infinity'::float8);

-- ---------------------------------------------------------------------
-- Trip
-- ---------------------------------------------------------------------
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_status_check"
  CHECK (status IN ('LOADING', 'IN_TRANSIT', 'ON_SITE', 'DISCHARGING', 'CLOSED'));

ALTER TABLE "Trip" ADD CONSTRAINT "Trip_volumeDeliveredM3_nonneg_finite"
  CHECK ("volumeDeliveredM3" IS NULL OR ("volumeDeliveredM3" >= 0 AND "volumeDeliveredM3" < 'Infinity'::float8));

ALTER TABLE "Trip" ADD CONSTRAINT "Trip_reclaimedVolumeM3_nonneg_finite"
  CHECK ("reclaimedVolumeM3" IS NULL OR ("reclaimedVolumeM3" >= 0 AND "reclaimedVolumeM3" < 'Infinity'::float8));

-- A trip's own lifecycle timestamps can never run backwards relative to
-- one another — each one is only ever stamped `now()` the instant its
-- own transition commits (src/lib/tripLifecycle.ts), but nothing at the
-- database level enforced that ordering.
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_timestamp_order"
  CHECK (
    ("departTime" IS NULL OR "departTime" >= "batchTime") AND
    ("arriveTime" IS NULL OR "departTime" IS NULL OR "arriveTime" >= "departTime") AND
    ("dischargeStart" IS NULL OR "arriveTime" IS NULL OR "dischargeStart" >= "arriveTime") AND
    ("dischargeEnd" IS NULL OR "dischargeStart" IS NULL OR "dischargeEnd" >= "dischargeStart")
  );

-- One person can't crew both positions of the same pump on the same trip.
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_pump_crew_distinct"
  CHECK ("pumpOperatorId" IS NULL OR "pumpAssistantId" IS NULL OR "pumpOperatorId" <> "pumpAssistantId");

-- Exactly one open (non-CLOSED) trip per truck/driver/pump — the actual,
-- final backstop behind claimTripResources' own busy checks
-- (src/lib/tripAssignment.ts). A partial unique index (not a plain one)
-- since any number of CLOSED trips legitimately share the same truck/
-- driver/pump over their working lives; only concurrently OPEN ones may
-- never overlap. Postgres unique indexes already treat NULL as "never
-- equal to another NULL", so pumpId being null (a chute delivery) never
-- collides with itself across many open trips.
CREATE UNIQUE INDEX "Trip_one_open_per_truck" ON "Trip" ("truckId") WHERE status <> 'CLOSED';
CREATE UNIQUE INDEX "Trip_one_open_per_driver" ON "Trip" ("driverId") WHERE status <> 'CLOSED';
CREATE UNIQUE INDEX "Trip_one_open_per_pump" ON "Trip" ("pumpId") WHERE status <> 'CLOSED' AND "pumpId" IS NOT NULL;

-- Pump crew collision across the operator AND assistant columns can't be
-- expressed as a single-column unique index (the same person could be
-- open as this trip's operator and another trip's ASSISTANT at once,
-- which a plain unique index on either column alone would miss) — a
-- trigger checks both columns against both columns of every other open
-- trip. Relies on the same Serializable-transaction convention every
-- concurrent dispatch/reassignment call in this app already uses
-- (startTrip/updateTripAssignment, production/actions.ts): two
-- concurrent transactions that would otherwise both pass this check for
-- the same crew member are caught by Postgres's own serializable-
-- snapshot conflict detection at commit time, same as the plain
-- findFirst-then-create truck-busy check this migration's unique indexes
-- above now additionally backstop directly.
CREATE OR REPLACE FUNCTION trip_check_pump_crew_collision() RETURNS trigger AS $$
BEGIN
  IF NEW.status = 'CLOSED' THEN
    RETURN NEW;
  END IF;
  IF NEW."pumpOperatorId" IS NOT NULL AND EXISTS (
    SELECT 1 FROM "Trip"
    WHERE id <> NEW.id AND status <> 'CLOSED'
      AND ("pumpOperatorId" = NEW."pumpOperatorId" OR "pumpAssistantId" = NEW."pumpOperatorId")
  ) THEN
    RAISE EXCEPTION 'Pump crew member % is already the operator or assistant on another open trip', NEW."pumpOperatorId";
  END IF;
  IF NEW."pumpAssistantId" IS NOT NULL AND EXISTS (
    SELECT 1 FROM "Trip"
    WHERE id <> NEW.id AND status <> 'CLOSED'
      AND ("pumpOperatorId" = NEW."pumpAssistantId" OR "pumpAssistantId" = NEW."pumpAssistantId")
  ) THEN
    RAISE EXCEPTION 'Pump crew member % is already the operator or assistant on another open trip', NEW."pumpAssistantId";
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trip_pump_crew_collision_check
  BEFORE INSERT OR UPDATE ON "Trip"
  FOR EACH ROW EXECUTE FUNCTION trip_check_pump_crew_collision();

-- ---------------------------------------------------------------------
-- DrumReturn
-- ---------------------------------------------------------------------
-- Matches the closed allow-lists src/lib/tripLifecycle.ts now enforces
-- in code (RETURN_REASON_CODES/RETURN_FATES, PL-P2-04) — real DB-level
-- guardrails behind the application-layer check, same posture as every
-- other status/enum-shaped free-string column this migration hardens.
ALTER TABLE "DrumReturn" ADD CONSTRAINT "DrumReturn_disposition_check"
  CHECK (disposition IN ('NO_CHARGE', 'FULL_WASTE', 'PARTIAL_CREDIT'));

ALTER TABLE "DrumReturn" ADD CONSTRAINT "DrumReturn_reasonCode_check"
  CHECK ("reasonCode" IS NULL OR "reasonCode" IN ('CUSTOMER_CANCELLED', 'SITE_NOT_READY', 'OVER_ORDERED', 'ACCESS_BLOCKED', 'QUALITY_REJECTED', 'TRAFFIC_DELAY', 'OTHER'));

ALTER TABLE "DrumReturn" ADD CONSTRAINT "DrumReturn_fate_check"
  CHECK (fate IS NULL OR fate IN ('DUMPED', 'RECLAIMED'));

ALTER TABLE "DrumReturn" ADD CONSTRAINT "DrumReturn_returnedVolumeM3_positive_finite"
  CHECK ("returnedVolumeM3" > 0 AND "returnedVolumeM3" < 'Infinity'::float8);

-- ---------------------------------------------------------------------
-- WasteIncidentMemo
-- ---------------------------------------------------------------------
ALTER TABLE "WasteIncidentMemo" ADD CONSTRAINT "WasteIncidentMemo_status_check"
  CHECK (status IN ('PENDING', 'APPROVED'));

ALTER TABLE "WasteIncidentMemo" ADD CONSTRAINT "WasteIncidentMemo_wastedVolumeM3_positive_finite"
  CHECK ("wastedVolumeM3" > 0 AND "wastedVolumeM3" < 'Infinity'::float8);

-- ---------------------------------------------------------------------
-- AuditEvent immutability — same hardening as InventoryMovement
-- (20260904185506_harden_inventory_movement), under its own distinct
-- bypass setting so the two tables' escape hatches can never be
-- confused. A correction is a NEW audit event, never an edit of one
-- already on file; nothing legitimate ever needs to UPDATE or DELETE a
-- posted row. The bypass exists solely for test fixture teardown (see
-- tests/reservationMixRevision.test.ts's deleteAuditEvents) — never set
-- by any application code path.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION audit_event_block_mutation() RETURNS trigger AS $$
BEGIN
  IF current_setting('app.bypass_audit_event_immutability', true) = 'on' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;
  RAISE EXCEPTION 'AuditEvent rows are immutable — insert a new event instead of using %', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_event_no_update
  BEFORE UPDATE ON "AuditEvent"
  FOR EACH ROW EXECUTE FUNCTION audit_event_block_mutation();

CREATE TRIGGER audit_event_no_delete
  BEFORE DELETE ON "AuditEvent"
  FOR EACH ROW EXECUTE FUNCTION audit_event_block_mutation();
