-- Hand-written (not generated by `prisma migrate diff`) — CHECK
-- constraints and triggers aren't expressible in schema.prisma for this
-- Prisma version, so this migration exists outside the normal
-- diff-from-schema workflow. Table is empty in every environment this
-- has been applied to so far, so none of this can conflict with existing
-- rows.

-- Value/relationship validation for InventoryMovement's polymorphic and
-- free-string columns (storageType/movementType/sourceType/unit aren't
-- real Postgres enums, matching how every other status/type column in
-- this schema is modeled — see e.g. BatchTicket.status's own comment —
-- but this table's rows are meant to be a permanent financial/inventory
-- record, so it gets real DB-level guardrails the rest of the schema
-- doesn't).
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_storageType_check"
  CHECK ("storageType" IN ('SILO', 'HOPPER', 'CHEMICAL_TANK'));

ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_unit_check"
  CHECK ("unit" IN ('TONS', 'LITERS'));

ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_movementType_check"
  CHECK ("movementType" IN ('BATCH_COMPLETION', 'BATCH_COMPLETION_REVERSAL', 'RECLAIM_CREDIT'));

ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_sourceType_check"
  CHECK ("sourceType" IN ('BatchTicket', 'Trip'));

-- A chemical tank is always metered in liters, a silo/hopper always in
-- tons — this pairing must never drift apart (src/lib/inventoryLedger.ts
-- already enforces it in code; this is the same rule enforced again at
-- the row level).
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_storage_unit_match"
  CHECK (
    ("storageType" = 'CHEMICAL_TANK' AND "unit" = 'LITERS') OR
    ("storageType" IN ('SILO', 'HOPPER') AND "unit" = 'TONS')
  );

-- A zero-quantity movement isn't a real event — nothing in this app ever
-- intends to post one.
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_quantity_nonzero"
  CHECK ("quantity" <> 0);

-- Immutability enforced at the database, not only by the app never
-- calling .update()/.delete() on this model (previously the only guard —
-- a source-code regex test, bypassable by raw SQL or a differently named
-- code path). A correction posts a new opposite-signed row instead (see
-- reverseBatchTicket in src/lib/batchCompletion.ts); nothing legitimate
-- ever needs to UPDATE or DELETE a posted row. The bypass flag exists
-- solely for test fixture cleanup (see tests/batchCompletion.test.ts,
-- which SET LOCALs it inside its own teardown transaction) — never set
-- by any application code path.
CREATE OR REPLACE FUNCTION inventory_movement_block_mutation() RETURNS trigger AS $$
BEGIN
  IF current_setting('app.bypass_movement_immutability', true) = 'on' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;
  RAISE EXCEPTION 'InventoryMovement rows are immutable — insert a reversing movement instead of using %', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER inventory_movement_no_update
  BEFORE UPDATE ON "InventoryMovement"
  FOR EACH ROW EXECUTE FUNCTION inventory_movement_block_mutation();

CREATE TRIGGER inventory_movement_no_delete
  BEFORE DELETE ON "InventoryMovement"
  FOR EACH ROW EXECUTE FUNCTION inventory_movement_block_mutation();
