-- Hand-written, not generated by `prisma migrate diff`, for the same
-- reason as 20260904185506_harden_inventory_movement: CHECK constraints,
-- triggers, and partial unique indexes aren't expressible in
-- schema.prisma for this Prisma version. The FK ON DELETE changes below
-- ARE expressible (schema.prisma's own relation annotations already
-- reflect them, so they'd also be produced by a plain diff) — kept here
-- alongside the hand-written pieces so the whole "make revision history
-- actually immutable" fix lands as one migration, matching how the
-- InventoryMovement hardening migration did the same.
--
-- Review finding RMR-P1-02: the original migration's schema comment
-- already claimed ReservationMixRevision/ReservationMixRevisionComponent
-- are "immutable once created, same posture as InventoryMovement" — but
-- nothing in the database actually enforced that. This migration closes
-- that gap.

-- ReservationMixRevisionComponent.revisionId used to CASCADE on delete —
-- deleting a used revision would silently take its components with it.
-- RESTRICT instead: a revision (and its components) can never be
-- deleted at all in practice once the immutability triggers below exist,
-- but this FK is the belt-and-suspenders backstop if that trigger is
-- ever bypassed for something the app didn't intend.
ALTER TABLE "ReservationMixRevisionComponent" DROP CONSTRAINT "ReservationMixRevisionComponent_revisionId_fkey";
ALTER TABLE "ReservationMixRevisionComponent" ADD CONSTRAINT "ReservationMixRevisionComponent_revisionId_fkey"
  FOREIGN KEY ("revisionId") REFERENCES "ReservationMixRevision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- BatchTicket.reservationMixRevisionId used to SET NULL on delete —
-- deleting a used revision would silently erase a released ticket's own
-- record of which revision it was actually built from. RESTRICT instead:
-- a ticket's provenance link must never be silently detached.
ALTER TABLE "BatchTicket" DROP CONSTRAINT "BatchTicket_reservationMixRevisionId_fkey";
ALTER TABLE "BatchTicket" ADD CONSTRAINT "BatchTicket_reservationMixRevisionId_fkey"
  FOREIGN KEY ("reservationMixRevisionId") REFERENCES "ReservationMixRevision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- status was an unrestricted free-string column — same real-DB-level
-- guardrail every other hardened status/type column in this schema gets
-- (see e.g. InventoryMovement's own CHECK constraints).
ALTER TABLE "ReservationMixRevision" ADD CONSTRAINT "ReservationMixRevision_status_check"
  CHECK ("status" IN ('ACTIVE', 'SUPERSEDED', 'CANCELLED'));

-- A zero/negative component quantity is never a legitimate edit — same
-- rule saveReservationMixRevision already enforces in code, repeated
-- here at the row level.
ALTER TABLE "ReservationMixRevisionComponent" ADD CONSTRAINT "ReservationMixRevisionComponent_designMassKgPerM3_positive"
  CHECK ("designMassKgPerM3" > 0);

-- The actual "one ACTIVE revision per reservation" invariant, enforced at
-- the database rather than only by saveReservationMixRevision's own
-- Serializable supersede-then-create pattern — same claim-via-constraint
-- posture as ShortageOverrideRequest_one_active_per_ticket. A concurrent
-- create colliding on this now surfaces as a typed, retryable Postgres
-- unique-violation instead of silently depending on transaction ordering
-- alone.
CREATE UNIQUE INDEX "ReservationMixRevision_one_active_per_reservation"
  ON "ReservationMixRevision" ("reservationId")
  WHERE "status" = 'ACTIVE';

-- Immutability for ReservationMixRevisionComponent — no legitimate code
-- path ever updates or deletes a component row once created (a save
-- always creates a whole new revision with its own new component rows
-- instead). Same bypass-flag shape as InventoryMovement's own trigger,
-- under a component-specific setting name so the two tables' test-only
-- escape hatches can never be confused with each other.
CREATE OR REPLACE FUNCTION reservation_mix_revision_component_block_mutation() RETURNS trigger AS $$
BEGIN
  IF current_setting('app.bypass_reservation_mix_revision_immutability', true) = 'on' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;
  RAISE EXCEPTION 'ReservationMixRevisionComponent rows are immutable — create a new revision instead of using %', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER reservation_mix_revision_component_no_update
  BEFORE UPDATE ON "ReservationMixRevisionComponent"
  FOR EACH ROW EXECUTE FUNCTION reservation_mix_revision_component_block_mutation();

CREATE TRIGGER reservation_mix_revision_component_no_delete
  BEFORE DELETE ON "ReservationMixRevisionComponent"
  FOR EACH ROW EXECUTE FUNCTION reservation_mix_revision_component_block_mutation();

-- ReservationMixRevision itself is never deleted, full stop — a
-- cancelled/superseded revision stays on file permanently (see the
-- model's own comment).
CREATE OR REPLACE FUNCTION reservation_mix_revision_block_delete() RETURNS trigger AS $$
BEGIN
  IF current_setting('app.bypass_reservation_mix_revision_immutability', true) = 'on' THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'ReservationMixRevision rows are permanent history — cancel or supersede instead of using %', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER reservation_mix_revision_no_delete
  BEFORE DELETE ON "ReservationMixRevision"
  FOR EACH ROW EXECUTE FUNCTION reservation_mix_revision_block_delete();

-- ...but its status/resolvedAt/resolvedById DO legitimately change —
-- exactly once, when saveReservationMixRevision supersedes it or
-- cancelActiveReservationMixRevision cancels it. Every other column
-- (reservationId, mixId, revisionNumber, reason, createdById, createdAt)
-- is frozen the moment the row is created; changing any of those would
-- rewrite what actually happened, not just record its resolution.
CREATE OR REPLACE FUNCTION reservation_mix_revision_restrict_update() RETURNS trigger AS $$
BEGIN
  IF current_setting('app.bypass_reservation_mix_revision_immutability', true) = 'on' THEN
    RETURN NEW;
  END IF;
  IF NEW."reservationId" IS DISTINCT FROM OLD."reservationId"
     OR NEW."mixId" IS DISTINCT FROM OLD."mixId"
     OR NEW."revisionNumber" IS DISTINCT FROM OLD."revisionNumber"
     OR NEW."reason" IS DISTINCT FROM OLD."reason"
     OR NEW."createdById" IS DISTINCT FROM OLD."createdById"
     OR NEW."createdAt" IS DISTINCT FROM OLD."createdAt" THEN
    RAISE EXCEPTION 'ReservationMixRevision rows are immutable except status/resolvedAt/resolvedById — insert a new revision instead';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER reservation_mix_revision_restrict_update
  BEFORE UPDATE ON "ReservationMixRevision"
  FOR EACH ROW EXECUTE FUNCTION reservation_mix_revision_restrict_update();
