import type { ReactNode } from "react";
import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePageAccess } from "@/lib/session";
import { getDictionary } from "@/lib/i18n";
import { PrintButton } from "@/components/PrintButton";

// A fixed bilingual printed form (SASO/ASTM-style RMC delivery note, per
// the sample the plant already uses) — deliberately NOT run through the
// app's own locale dictionary the way normal UI chrome is: the real paper
// document always carries both languages together regardless of which
// locale the person printing it happens to be browsing in, so every label
// here is hardcoded EN+AR rather than switched by dict.
const L = {
  docTitleAr: "تذكرة توريد خرسانة جاهزة",
  docTitleEn: "RMC Delivery Note",
  astm: "ASTM: 370",
  bookingRef: "Booking Ref. رقم التذكرة",
  customerCode: "Code كود العميل",
  customerName: "Customer Name اسم العميل",
  item: "Item رمز الصنف",
  itemDescription: "Item Description وصف الصنف",
  cementType: "Cement Type نوع الأسمنت",
  slumpFlow: "Slump / flow الهبوط",
  maxTemp: "Max Temp(c) أقصى حرارة",
  waterCement: "Water/cement نسبة الماء/الأسمنت",
  maxAggrSize: "Max Aggr Size أقصى حجم الركام",
  plant: "Plant المحطة",
  pump: "Pump المضخة",
  mixer: "Mixer الشاحنة",
  driver: "Driver السائق",
  location: "Location الموقع",
  extDriver: "EXT Driver السائق الخارجي",
  type: "Type النوع",
  addOnDiscount: "Add on or Discount Option الاضافة/الخصم",
  leaveTime: "Leave time وقت المغادرة",
  returnTime: "Return Time وقت العودة",
  pouringStart: "Pouring Start Time وقت بداية الصب",
  pouringEnd: "Pouring End Time وقت نهاية الصب",
  qtyDelivered: "QTY Delivered كمية المورد",
  qtyInMix: "QTY In Mix الكمية في الشاحنة",
  totalQty: "Total Qty اجمالى الكمية",
  waterNote: "Any Addition of water to the mix will be customer's responsibility\nان اضافة اي ماء الى الخلطة على مسؤولية العميل",
  operator: "Operator",
  qualityControl: "Quality Control",
  customer: "Customer",
  withoutPump: "Without Pump",
  none: "None",
} as const;

// Plain inline styles rather than Tailwind utility classes for anything
// needing a precise value (border color, exact font sizes, the header's
// column widths) — this route's arbitrary-value classes (text-[10px],
// border-[#000], grid-cols-[140px_1fr]) weren't being generated by the
// dev server even after a full cache clear, while standard named classes
// on the same page worked fine; inline styles sidestep that entirely and
// are arguably the more honest tool anyway for a fixed print layout.
const cellBorder = { border: "1px solid #000" };

function Cell({ label, value, className = "" }: { label: string; value: ReactNode; className?: string }) {
  return (
    <div style={cellBorder} className={`px-2 py-1.5 ${className}`}>
      <div style={{ fontSize: "10px" }} className="font-semibold leading-tight">{label}</div>
      <div style={{ fontSize: "13px" }} className="mt-0.5" dir="ltr">{value ?? "—"}</div>
    </div>
  );
}

function fmtTime(d: Date | null | undefined) {
  if (!d) return null;
  return new Date(d).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: true });
}

export default async function DeliveryNotePage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requirePageAccess("production");
  const { id } = await params;
  const { dict } = await getDictionary();

  const ticket = await prisma.batchTicket.findUnique({
    where: { id },
    include: {
      reservation: { include: { project: { include: { customer: true } } } },
      mix: true,
      plant: { include: { site: true } },
      trip: { include: { truck: true, driver: true, pump: true } },
    },
  });
  // Printable only once the mixer has actually been loaded and dispatched
  // (a Trip exists) — matches when this document is meant to be issued.
  if (!ticket || !ticket.trip) notFound();

  const { trip, reservation, mix, plant } = ticket;
  const structureType = reservation.structureType
    ? dict.structureTypes[reservation.structureType as keyof typeof dict.structureTypes] ?? reservation.structureType
    : null;
  const cementType = reservation.cementType ?? L.none;
  const slumpFlow =
    reservation.slumpRequestedMm != null
      ? `${reservation.slumpRequestedMm}${reservation.slumpToleranceMm != null ? ` ± ${reservation.slumpToleranceMm}` : ""} mm`
      : null;

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-4">
      <div className="no-print flex justify-end">
        <PrintButton label={dict.modules.production.detail.printTicket} />
      </div>

      <div dir="ltr" style={{ background: "#fff", color: "#000" }} className="flex flex-col gap-3 p-6">
        <div style={{ ...cellBorder, display: "grid", gridTemplateColumns: "140px 1fr" }}>
          <div
            style={{ ...cellBorder, borderTop: "none", borderBottom: "none", borderInlineStart: "none", fontSize: "10px" }}
            className="flex items-center justify-center p-2 text-center font-bold leading-tight"
          >
            SASO
            <br />
            QUALITY MARK
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 2fr auto" }} className="items-center">
            <div className="p-2 text-sm font-bold">{L.astm}</div>
            <div className="p-2 text-center">
              <div className="text-lg font-bold">{L.docTitleAr}</div>
              <div className="text-base font-semibold">{L.docTitleEn}</div>
              <div className="mt-1 text-sm">
                {plant.name} — {plant.site.name}
                <span className="ms-2 font-mono">{plant.site.code}</span>
              </div>
            </div>
            <div className="p-2 text-end text-sm font-semibold">
              {new Date(trip.batchTime).toLocaleDateString("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" })}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-3">
          <Cell label={L.bookingRef} value={ticket.ticketNumber} />
          <Cell label={L.customerCode} value={reservation.project.customer.code ?? "—"} />
          <Cell label={L.customerName} value={reservation.project.customer.legalName} className="text-end" />
        </div>

        <div className="grid grid-cols-2">
          <Cell label={L.item} value={mix.code} />
          <Cell label={L.itemDescription} value={mix.grade} className="text-end" />
        </div>

        <div className="grid grid-cols-5">
          <Cell label={L.cementType} value={cementType} />
          <Cell label={L.slumpFlow} value={slumpFlow} />
          <Cell label={L.maxTemp} value={reservation.temperatureC ?? null} />
          <Cell label={L.waterCement} value={mix.wcRatio.toFixed(2)} />
          <Cell label={L.maxAggrSize} value={null} />
        </div>

        <div className="grid grid-cols-5">
          <Cell label={L.plant} value={plant.name} />
          <Cell label={L.pump} value={trip.pump?.code ?? L.withoutPump} />
          <Cell label={L.mixer} value={trip.truck.code} />
          <Cell label={L.driver} value={trip.driver.name} />
          <Cell label={L.location} value={reservation.siteLocation ?? null} />
        </div>

        <div className="grid grid-cols-4">
          <Cell label={L.mixer} value={trip.truck.code} />
          <Cell label={L.extDriver} value={null} />
          <Cell label={L.type} value={structureType} />
          <Cell label={L.addOnDiscount} value={null} />
        </div>

        <div className="grid grid-cols-4">
          <Cell label={L.leaveTime} value={fmtTime(trip.departTime)} />
          <Cell label={L.returnTime} value={null} />
          <Cell label={L.pouringStart} value={fmtTime(trip.dischargeStart)} />
          <Cell label={L.pouringEnd} value={fmtTime(trip.dischargeEnd)} />
        </div>

        <div className="grid grid-cols-3">
          <Cell label={L.qtyDelivered} value={(trip.volumeDeliveredM3 ?? 0).toFixed(2)} className="text-center" />
          <Cell label={L.qtyInMix} value={ticket.volumeM3.toFixed(2)} className="text-center" />
          <Cell label={L.totalQty} value={ticket.volumeM3.toFixed(2)} className="text-center" />
        </div>

        <div style={cellBorder} className="whitespace-pre-line p-3 text-center text-sm font-semibold">{L.waterNote}</div>

        <div className="grid grid-cols-4">
          <Cell label={L.operator} value={user.name} />
          <Cell label={L.driver} value={null} />
          <Cell label={L.qualityControl} value={null} />
          <Cell label={L.customer} value={null} />
        </div>
      </div>

      <div className="no-print">
        <Link href={`/production/${ticket.id}`} className="text-sm font-medium text-accent-strong hover:underline">
          ← {dict.field.cancel}
        </Link>
      </div>
    </div>
  );
}
